### ISSUE TITLE
[GLOBAL] Tasks Incremento 8

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-thirema#10]
## Tasks incremento 8

> Entro il 29 marzo 2020, tasks in ordine cronologico

- [x] Verbale 19 interno (23 marzo 2020) @giovd8  --> `entro giovedì 🔥 `
- [x] Rif. issue #326 in swe-docs @aletomm   --> `entro giovedì 🔥 `
- [x] Sistemare AdR con quanto detto nella revisione del professore. @lorenzodeinegri  --> `entro giovedì 🔥 `
- [ ] Rif. issue #325 in swe-docs @giovd8 @Maxelweb @nfrison  --> `entro giovedì 🔥 `
- [x] Rif. issue #327 in swe-docs @lorenzodeinegri  --> `entro giovedì 🔥 `
- [x] Aggiornamento versione +b0.12  @Maxelweb  --> `entro giovedì 🔥 `
- [x] Mail per Tullio @Maxelweb  --> `entro giovedì 🔥 `
- [x] Design pattern da applicare e inizio manuale del manutentore @lorenzodeinegri @Maxelweb @aletomm 
- [ ] Continuazione form webapp, lista dispositivi e test dei grafici @BroHPotato @giovd8 
  - [x] form;
  - [ ] lista dispositivi;
  - [x] grafi;
- [ ] API per le chiamate al timeseriesDB per visualizzare i grafici @FouadM96 @nfrison 

---

> Richiesta col professor Vardanega mercoledì / giovedì

- [ ] Manuale utente, cominciare a stilare la parte di login (video?) --> `da giovedì a domenica 🔥 `
- [ ] Metriche, rischi e miglioramenti (incremento 7) --> `da venerdì a domenica 🔥 `
