### ISSUE TITLE
[GLOBAL] Tasks Incremento 9

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-thirema#11]
## Tasks incremento 9

> Entro il 05 aprile 2020

- [x] Realizzazione API in concomitanza con la parte utente @nfrison @FouadM96 
- [x] Realizzazione parte utente / inizio parte moderatore (backend) @BroHPotato 
- [x] Realizzazione parte utente / inizio parte moderatore (frontend) @giovd8 @aletomm @Maxelweb 
- [ ] ~Versione documenti da riscrivere NdP~ @Maxelweb 
- [x] Sistemare metriche @Maxelweb 
- [x] Ricontrollare metriche da riattivare, stasera dopo cena @lorenzodeinegri  --> `entro lunedì 🔥 `
- [ ] ~Manuale utente, cominciare a registrare la parte di login e dashboard~ @aletomm @Maxelweb 
- [ ] Metriche, Test, rischi e miglioramenti (incremento 7)  --> `entro venerdì 🔥 ` @FouadM96 (*)
- [ ] Metriche, Test, rischi e miglioramenti (incremento 8)  --> `entro venerdì 🔥 `  @FouadM96 (*)
- [ ] Sistemare Piano di progetto con il raggruppamento degli incrementi @giovd8 @lorenzodeinegri  --> `entro venerdì 🔥 `
- [x] Realizzare docker-compose per l'avvio completo ~@aletomm~ @Maxelweb @lorenzodeinegri 
- [x] Release della baseline `+b0.13` --> `entro venerdì 🔥 ` @Maxelweb 

> Prossimi task

- [ ] Sistemare i registri delle modifiche @lorenzodeinegri
- [x] RA-P-2 e CMB-CA-27
- [ ] Sistemare Registri delle modifiche
- [x] Aggiungere gli Standard di codifica nel NdP
- [x] Iniziare Diagrammi classi
- [ ] Versione documenti da riscrivere NdP
