### ISSUE TITLE
[GLOBAL] Tasks Incremento 12

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-thirema#17]
## Tasks incremento 12

> entro il 30 aprile 2019

- [x] Rilascio 0.15 @Maxelweb 
- [x] Rilascio 0.16 @Maxelweb 
- [x] Logo per il prodotto Riot @Maxelweb 
- [x] Sistemare tutti dockerfile e gli install script in modo da poter avviare e stoppare i singoli container @lorenzodeinegri 
- [x] Sistemare la configurazione del gateway con quanto riportato nella Issue 40 (swe-gateway) @nfrison 
- [x] Concludere la parte API per quanto riguarda l'invio della nuova configurazione del gateway @FouadM96 
- [x] Sistemare la webapp per quanto riguarda i dati dei sensori (caricare i dati dalle API) @BroHPotato 
- [x] Concludere la parte admin della webapp [Frontend] @aletomm @lorenzodeinegri 
- [x] Concludere la parte admin della webapp [Backend] @BroHPotato 
- [x] Invio comandi tramite Telegram solo per gli amministratori @Maxelweb @giovd8 
- [x] Gestione invio comandi di telegram dalle API @FouadM96
- [x] Cambiamento del funzionamento di un sensore del simulatore di dispositivi per adattarlo alla ricezione di un comando @nfrison 

### Risultati RQ

> Da fare dopo che esce la valuzione della revisione

- [ ] Sistemazione dei documenti
- [ ] Rischi incontrati, Metriche, valutazioni di miglioramento, consuntivo di periodo, preventivo a finire 
- [ ] Sistemare il manuale utente
- [ ] Sistemare il manuale dello sviluppatore

**Comment by Maxelweb** [comment]
> Conclusione dello sviluppo tassativo per il giorno domenica 3 maggio
> Presentazione anticipatoria azienda: 8 maggio
