### ISSUE TITLE
[GLOBAL] Tasks validazione 1

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-thirema#19]
# Tasks Validazione 1 

## Riunioni 

- [x] **Prof. Vardanega:** 5 maggio, ore 18:00
- [x] **Prof. Cardin:** 6 maggio, ore 17:30
- [ ] **SanMarco Informatica (demo):** 14 maggio, ore 17:15

### 🔥 🔥 [VALIDAZIONE 1](https://github.com/RedRoundRobin/swe-thirema/issues/20) 🔥 🔥 

> entro 11 maggio 2020

- [x] Verbale esterno con Tullio (con considerazioni post Tullio) @BroHPotato 
- [ ] Far funzionare il `mr_wolf.sh` in versione installazione @Maxelweb @lorenzodeinegri 
- [x] Registrare versione +b0.17 @Maxelweb 
- [x] Correzione bug sonarcloud nella webapp [backend/frontend] @BroHPotato @Maxelweb 
- [ ] Redigere verbale interno [issue #380](https://github.com/RedRoundRobin/swe-docs/issues/380) @nfrison 
- [ ] Correzione bug sonarcloud nelle API @FouadM96 @nfrison 
- [x] Correzione bug sonarcloud in Kafka-db @lorenzodeinegri 
- [x] Correzione bug sonarcloud in Gateway @nfrison 
- [ ] Correzione bug sonarcloud in Telegram, ampliare con le emoji se possibile la parte di ricezione codici TFA e alerts @giovd8 
- [ ] Ampliare il manuale del manutentore con le parti segnalate da Cardin @aletomm @giovd8 
- [ ] Rischi incontrati, Metriche, valutazioni di miglioramento @FouadM96 
- [x] Obiettivi per la valutazioni di miglioramento @lorenzodeinegri @FouadM96 
- [x] Consuntivo di periodo, preventivo a finire @giovd8 
- [ ] Sistemare il manuale utente / sviluppatore @aletomm @nfrison @Maxelweb 
- [x] Preparare una demo per SanMarco Informatica `entro 14 maggio` (*)

**Comment by aletomm** [comment]
## Domande per Tullio

- [ ] Manuale utente con i video o è necessario avere delle descrizioni testuali aggiuntive?
- [ ] §B-§C: questi contenuti sono da correlare con l’attuazione del ciclo PDCA, e quindi da mettere in relazione con specifici obiettivi di miglioramento.

**Comment by Maxelweb** [comment]
## Domande per Riccardo

- [ ] Cosa non andava nei video che abbiamo accuratamente ordinato e rilasciato nel manuale utente?

**Comment by aletomm** [comment]
## Soluzione per manuale utente
Aggiungere per ogni sezione (es: gestione utente ) una descrizione generale del video. Poi aggiungere delle sottosezioni con uno screenshot della schermata ed una breve descrizione (può essere presa dalla scaletta su Drive).

**Comment by Maxelweb** [comment]
## Risposte Cardin

- Ci deve essere un manuale PDF con anche le informazioni scritte, non solo link esterni a video.
- Bisogna riportare dentro il manuale utente lo specifico dettaglio delle funzionalità.
- Non servono i video per l’amministrazione. 
- Cambiare il titolo Generale / Membro, non adeguato.
- Riferimento alle tecnologie: non serve la home per le tecnologie, usare o rimuovere i link inutili.
- Descrizione componenti diagrammi: fare solo le interazioni con le componenti più interessanti.
- API si possono aggiungere al documento.

**Comment by Maxelweb** [comment]
Aggiunti i task per la validazione 1
