### ISSUE TITLE
[GLOBAL] Tasks Incremento 7

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-thirema#8]
## Tasks incremento 7

> Entro il 22 marzo 2020, tasks in ordine cronologico

- [x] Modificare le relazioni dei database in modo da identificare id_reale dei sensori / dispositivi e id_logico (primary key). @lorenzodeinegri --> `entro martedì` 🔥 
- [x] Aggiungere auto_increment ai valori mancanti. @lorenzodeinegri --> `entro martedì` 🔥 
- [x] Sistemare il no-sql con le primary key di solo time e id_log. @lorenzodeinegri --> `entro martedì` 🔥 
- [x] Aggiungere 1 ente e 3 utenti. @lorenzodeinegri --> `entro martedì` 🔥 
- [x] Ricerca strumenti e configurazione dei controlli di sintassi e dello stile del codice su tutte le repo (autismo) @lorenzodeinegri @Maxelweb  --> `entro mercoledì` 🔥 
- [ ] Ricercare alcuni design pattern da applicare al codice riutilizzato nel PoC @lorenzodeinegri 
- [x] Rivedere e concludere l'adapter del database @aletomm --> `entro martedì` 🔥 
- [x] Registrazione della nuova versione del prodotto @Maxelweb  --> `entro martedì sera` 🔥 
- [x] Realizzare Github actions per eseguire i controlli sul funzionamento del codice in tutti i branch @Maxelweb @aletomm @giovd8  
- [x] Prima configurazione del bot Telegram, registrazione canale e invio codici di autenticazione a due fattori @giovd8 @aletomm 
- [x] Implementazione delle altre API rimanenti, una volta concluso il DB @FouadM96 @nfrison 
- [x] Implementazione del tema della webapp ~~@BroHPotato~~ @Maxelweb  --> `entro mercoledì` 🔥 
- [x] Implementazione del login della webapp @BroHPotato @Maxelweb  
- [x] Contattare Alex per chiedergli se i gateway vanno gestiti dalla web app o solo a livello di database. @Maxelweb --> `entro martedì` 🔥 

> **PROSSIMO INCONTRO GIOVEDI' 10:00**

- Analisi dei rischi 
- Valutazioni di miglioramento
- Consuntivo di periodo e preventivo a finire
- Rilevazioni delle metriche di qualità

**Comment by Maxelweb** [comment]
- [ ] Aggiungere caso d'uso per la gestione dei gateway (add/edit/remove)
- [ ] Aggiungere il campo Gateway alla registrazione del dispositivo
- [ ] Aggiungere caso d'uso per la bozza di invio della nuova configurazione ai gateway
